services:
  db:
    build: 
      context: .
      target: dev
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: findmyprebuilt
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db-testing:
    image: postgres:latest
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  redis-stack:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  postgres_data: